version: 0.2
run-as: root


phases:
  pre_build:
    commands:
      - nodejs --version
  build:
    commands:
      - echo Build started on `date`
      - echo installing node modules
      - npm install
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
